version: '3'
services:
  mongo:
    image: mongo:3.6
    networks:
      - gateway
  food-saver-server:
    image: food-saver-node_node
    networks:
      - gateway
    command: npm run debug
    container_name: food-saver-server
    networks:
      - gateway
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI_LOCAL=mongodb://mongo:27017/test 
      - PORT=8080
    links:
      - mongo 
    depends_on: 
      - mongo 
    volumes:
      - .:/starter
      - /starter/node_modules
  food-saver-client:
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: food-saver-client
    environment:
      - PORT=8090
      - VUE_APP_BACKEND_URL=http://local-google-oauth-url.com:8080/api/
    ports:
     - "8090:8090"
    volumes:
     - .:/app
     - /app/node_modules
    #links:
    # - food-saver-server 
    #depends_on: 
    # - food-saver-server 
networks:
  gateway: {}
     