version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
     - "8080:8080"
    environment:
     - MONGODB_URI=mongodb://mongo:27017/test 
     - OPENSHIFT_NODEJS_PORT=8080
    volumes:
     - .:/app
     - /app/node_modules
     