export const FETCH_END = 'setArticles';
export const FETCH_START = 'setLoading';
export const PURGE_AUTH = 'logOut';
export const SET_ARTICLE = 'setArticle';
export const SET_AUTH = 'setUser';
export const SET_COMMENTS = 'setComments';
export const SET_ERROR = 'setError';
export const SET_PROFILE = 'setProfile';
export const SET_TAGS = 'setTags';
export const TAG_ADD = 'addTag';
export const TAG_REMOVE = 'removeTag';
export const UPDATE_ARTICLE_IN_LIST = 'updateArticleInList';
export const RESET_STATE = 'resetModuleState';

export enum MutationTypes {
  FETCH_END = 'setArticles',
  FETCH_START = 'setLoading',
  PURGE_AUTH = 'logOut',
  SET_ARTICLE = 'setArticle',
  SET_AUTH = 'setUser',
  SET_COMMENTS = 'setComments',
  SET_ERROR = 'setError',
  SET_PROFILE = 'setProfile',
  SET_TAGS = 'setTags',
  TAG_ADD = 'addTag',
  TAG_REMOVE = 'removeTag',
  UPDATE_ARTICLE_IN_LIST = 'updateArticleInList',
  RESET_STATE = 'resetModuleState',
  SET_POKEMON_LIST = 'setPokemonList',
  SET_POKEMON_ERRORS = 'setPokemonErrors',
  SET_POKEMON_LOADING = 'setPokemonLoading',
  POKEMON_REMOVE = 'removePokemon',
  SET_ACTIVE_POKEMON = 'setActivePokemon',
  SET_ACTIVE_OPPORTUNITY = 'setActiveOpportunity',
  SET_OPPORTUNITY_LIST = 'setOpportunityList',
  SET_OPPORTUNITY_ERRORS = 'setOpportunityErrors',
  SET_OPPORTUNITY_LOADING = 'setOpportunityLoading',
  SET_PROFILE_LOADING = 'setProfileLoading',
  SET_PROFILE_ERRORS = 'setProfileErrors',
  OPPORTUNITY_ADD = 'addOpportunity',
  SET_CURRENT_POSITION = 'setCurrentPosition',
  SET_CHAT_LIST = 'setChatList',
  CHAT_ADD = 'addChat',
  MESSAGE_ADD = 'addMessage',
}
